name: Triggered Workflow

on:
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Workflow triggered successfully!"
